Feature/management
mju-likelion/ballantines pull request #10
Opened 2023-02-16 16:28 UTC by k0136000

운영진 및 회원(추후 기능 추가)회원가입 이메일 인증 전송 기능, 
운영진 패스워드 업데이트 기능 추가 하였습니다.
예외 필터 및 파이프 및 스웨거 api문서는 다음주 목요일 이내로 완성해서 올리도록 하겠습니다.

2023-02-18 09:25 UTC, ndaemy requested changes
리뷰가 많아서 일단 여기서 한 번 끊고 갈게요! 수정해주시면 그때 추가 리뷰 달겠습니당
수고하셨어요 💪

2023-02-18 09:25 UTC, ndaemy commented on src/api/managements/entities/user.entity.ts
> +@Entity('Managers')
👍 
요건 plural form 이 낫겠네요
application 을 제가 singular form 으로 했는데 제가 수정하겠습니다
좋은거 배워감

2023-02-18 09:25 UTC, ndaemy commented on src/api/managements/entities/user.entity.ts
> +  userInform: 'manager' | 'member';
1. 요건 userInform 이라고 하면 뭔지 확 와닿지 않는 느낌이에요. 다른 좋은 단어..가 없을까요?
2. 이거 어디에 쓰이는거죠..? Manager 면 모두가 manager 인거 아닌가요? 그 대표랑 운영진을 나누기 위해서 쓴거라면 네이밍을 수정하는게 좋을 것 같습니다!

2023-02-18 09:25 UTC, ndaemy commented on src/api/managements/entities/user.entity.ts
> +  userinform: 'manager' | 'member';
`userInform`!!

2023-02-18 09:25 UTC, ndaemy commented on src/api/managements/entities/user.entity.ts
> +  verifytoken: string;
`verifyToken`!!

2023-02-18 09:25 UTC, ndaemy commented on src/api/managements/managements.controller.ts
> +  async sendEmail(@Body() createUserDto: CreateUserDto) {
dto 는 data transfer object 의 줄임말이잖아요? 그러니까 sendEmail 에 대한 dto 라면 sendEmailDto 가 네이밍이 좀 더 맞지 않을까 싶어요! 어떻게 생각하시나요?

2023-02-18 09:25 UTC, ndaemy commented on src/api/managements/managements.controller.ts
> +  async registManager(@Body() updateUserDto: UpdateUserDto) {
오타있습니당
regist(x) register(o)

2023-02-18 09:25 UTC, ndaemy commented on src/api/managements/managements.service.ts
> +  private async saveManager(
위에서도 이미 한 리뷰인데, 메서드 간에는 빈 줄을 만들어주세요!

2023-02-18 09:27 UTC, ndaemy commented
아 그리고 PR 이름도 바꿔주세요!

2023-02-19 05:40 UTC, k0136000 commented on src/api/managements/entities/user.entity.ts
> +  userInform: 'manager' | 'member';
나중에 제가 인가, 회원 이메일 전송 기능에 사용하려고 했던 정보인데 제가 착각했네요!
대표랑 운영진으로 나눠 사용하도록 하겠습니다:)

2023-02-19 05:41 UTC, k0136000 commented on src/api/managements/managements.controller.ts
> +  async sendEmail(@Body() createUserDto: CreateUserDto) {
생각해보니 그렇네요!!
수정하겠습니다:)

2023-02-19 16:28 UTC, closed without merging