전체 지원서, 각 회원 지원서 제공 API
mju-likelion/ballantines pull request #11
Opened 2023-02-16 19:23 UTC by ChoiWonYu

질문

- 기획안에 파트별 회원의 지원서를 가져오는 것에 대한 내용이 없는데 파트 별 회원의 지원서를 제공하는 API가 있어야 하는지
- 전체 지원서의 개수를 구할 때 단지 지원서 데이터 배열의 크기만을 위해 데이터 전체를 가져오는 것은 비효율적인 것 같은데 다른 방법이 있는지
-

2023-02-17 00:50 UTC, Sujin-Hasse commented
**기획안에 파트별 회원의 지원서를 가져오는 것에 대한 내용이 없는데 파트 별 회원의 지원서를 제공하는 API가 있어야 하는지**

이건 제가 놓친 부분인데 있어야 할 것 같아요..! 혹시 추가해주실 수 있다면 감사하겠습니다 ! :-)

2023-02-17 07:34 UTC, harksu commented
**전체 지원서의 개수를 구할 때 단지 지원서 데이터 배열의 크기만을 위해 데이터 전체를 가져오는 것은 비효율적인 것 같은데 다른 방법이 있는지**

전체 배열을 반환하고 그 배열의 길이를 구하는게 아니라, COUNT()연산을 typeORM을 통해서 구현하면 될 것 같다는 생각이 듭니다 🤔 

[이런느낌](https://www.tabnine.com/code/javascript/functions/typeorm/SelectQueryBuilder/getCount)

2023-02-17 07:35 UTC, harksu commented on src/api/applications/applications.service.ts
> +    //총 개수를 구할 수 있는 더 효율적인 방법..?
이건 conversation에 개인적인 의견을 남겨놓았습니다.

데이터가 필요한게 아니라 단순히 entity가 몇개인지 필요한거니까요!

2023-02-17 07:51 UTC, ChoiWonYu commented on src/api/applications/applications.service.ts
> +    //총 개수를 구할 수 있는 더 효율적인 방법..?
<img width="397" alt="image" src="https://user-images.githubusercontent.com/93238308/219583771-f3d12f7d-8dec-4a5b-8f92-2fa015e4b494.png">
👍👍감사함당

2023-02-17 15:36 UTC, harksu commented on src/api/applications/applications.service.ts
> +    const totalApplicationsCount = await this.applicationRepository.count({
지금 확인해보니까 converstaion에 링크를 제가 생각한걸 단게 아니였지만 그래두 👍

2023-02-18 09:39 UTC, ndaemy requested changes
마지막 리뷰때문에 Request changes 로 달아둡니다..!
리뷰의 리뷰 달아주시면 다음에 다시 리뷰하러 올게영 👋

2023-02-18 09:39 UTC, ndaemy commented on src/api/applications/applications.controller.ts
> +import { PagenationOptions } from './dto/find-application.dto';
pagination 이 맞습니다..!

2023-02-18 09:39 UTC, ndaemy commented on src/api/applications/dto/find-application.dto.ts
> +  page: string;
page 도 optional 로 가고 없을 경우에는 0번 페이지 (혹은 1번 페이지?) 를 주는게 나을 것 같아요..!

2023-02-18 09:39 UTC, ndaemy commented on src/api/applications/applications.controller.ts
> +  findAll(@Query() pagenationOptions: PagenationOptions) {
저도 이건 잘 몰라서 찾아봤어요.
dto 는 body일 때만 쓰는 느낌인데..? query 일때는 뭐라고 부르지? 해서 찾아봤는데 QueryDto 라고 부르는 경우가 있는 것 같더라구요
그래서 저는 PaginationQueryDto 정도로 이름 붙여보면 어떨까 하는데, 다른 아이디어 있으시면 그것도 좋구요!

2023-02-18 09:39 UTC, ndaemy commented on src/api/applications/applications.service.ts
> +    };
으으으음.. 객체지향 관점에서 보면 이건 여기가 아니라 dto 파일에 있어야 맞는 느낌같은데.. static method 로 보내버리는건 어떨까요?

2023-02-18 09:39 UTC, ndaemy commented on src/api/applications/applications.service.ts
> +      }),
오 이런게 가능하구나..

2023-02-18 11:05 UTC, ndaemy commented on src/api/applications/applications.controller.ts
> +  findAll(@Query() pagenationOptions: PagenationOptions) {
Query라는 말이 안들어가도 괜찮을까영?
이게 쿼리용 dto인지, body용 dto인지 dto 파일만 보고 알 수 있어야 하려나? 라는 생각에서 나온 의견입니다!

2023-02-18 11:50 UTC, ChoiWonYu commented on src/api/applications/applications.controller.ts
> +  findAll(@Query() pagenationOptions: PagenationOptions) {
음 그럼 PaginationQueryDto로 가겠습니당

2023-02-18 11:52 UTC, ChoiWonYu commented on src/api/applications/applications.service.ts
> +    };
저는 이건 entity 멤버 문자열에서 해당 멤버와 정렬 방법을 추출하는 메서드라 비즈니스 로직이라고 생각했습니다 dto에 있는 게 더 나을까요??

2023-02-18 20:53 UTC, ndaemy approved these changes
의견 달아둔건 의견일 뿐이라 approve 갈깁니다

2023-02-18 20:53 UTC, ndaemy commented on src/api/applications/applications.controller.ts
> +  //page를 number로 사용하기 위해서 추가
👍

2023-02-18 20:53 UTC, ndaemy commented on src/api/applications/applications.service.ts
> +    };
저는 이 메서드가 dto 객체를 부를때만 쓸 메서드라고 생각해서 dto 클래스에 있어야하나? 라는 관점이었어요!

2023-02-22 16:11 UTC, ndaemy approved these changes
파일명만 바꿔주세요! 나머진 괜찮을듯 합니다

2023-02-22 16:11 UTC, ndaemy commented on src/api/applications/dto/PaginationQueryDTO.ts
> +//위처럼 enum이 더 깔끔할 거 같은데 이걸 consts나 type 파일을 만들까요? 아니면 여기 둘까요?
이건 여기 둬도 될 것 같은데, 다른 곳에서도 사용되나요? 굳이 사용되는게 아니라면 export 하지 않아도 될 것 같습니다!

2023-02-22 16:11 UTC, ndaemy commented on src/api/applications/dto/PaginationQueryDTO.ts
> +import { Type } from 'class-transformer';
요거 파일명은 pagination-query.dto.ts 로 하는게 나을 듯 싶습니다!

2023-02-22 16:11 UTC, ndaemy commented on src/api/applications/dto/PaginationQueryDTO.ts
> +  @IsInt()
이 두개는 같은 역할을 하기 때문에 둘 다 들어가지 않아도 될 것 같아요!

2023-02-22 16:11 UTC, ndaemy commented on src/api/applications/dto/PaginationQueryDTO.ts
> +}
아까 잠깐 얘기했었지만, enum 쓴다고 죽는건 아니라서 그냥 써도 무방할듯 합니다

2023-02-22 19:23 UTC, ChoiWonYu commented on src/api/applications/dto/PaginationQueryDTO.ts
> +  @IsInt()
Type 데커레이터는 타입을 명시적으로 나타내는 역할도 하지만 순수 요청 객체를 dto 클래스 객체로 전환하는 과정에서 
타입 변환을 시켜주는 것 같아요!
실제로 해당 코드가 없을 때 에러가 발생합니다

2023-02-23 12:34 UTC, merged