코드리뷰 수정 및 운영진 로그인 기능 추가
mju-likelion/ballantines pull request #16
Opened 2023-02-20 20:04 UTC by k0136000

2023-02-20 20:06 UTC, k0136000 commented
운영진 로그인 기능 추가했습니다. 
DB에서 유저 체크하는 파이프는 구현되자마자 수정해서 업로드 하겠습니다.
constants.ts 이파일 지웠어야 했는데 올라갔네요..
코드 리뷰 받고 바로 삭제 하겠습니다!

2023-02-21 16:18 UTC, ndaemy commented
일단 다른것에 앞서서.. PR 은 수정할때마다 열 필요 없습니다!
브랜치 하나 따고 PR 한 번 열면, 코드리뷰를 하건 코드를 수정하건 머지를 하건 다 거기서 진행하면 돼요!

2023-02-21 16:20 UTC, ndaemy commented
1. 일단 그 전에 코드리뷰 했던 내용을 볼 수 없고,
2. PR 을 merge 없이 close 하는건 해당 PR에 사용된 코드들이 모종의 이유로 머지되지 않기로 했다 라는 의미도 포함하게 되어버려서 그렇습니다

2023-02-21 16:50 UTC, ndaemy requested changes
코드리뷰가 좀 많네요.. 화이팅입니다 💪

2023-02-21 16:50 UTC, ndaemy commented on src/api/auth/auth.module.ts
> +      signOptions: { expiresIn: process.env.JWT_EXPIRES_IN },
요걸 별도의 환경변수로 뺀 이유가 있나요?

2023-02-21 16:50 UTC, ndaemy commented on src/api/auth/auth.service.ts
> +  email: string;
혹시.. password 가 email 보다 순서가 앞인 이유가 있나요..?

2023-02-21 16:50 UTC, ndaemy commented on src/api/auth/auth.service.ts
> +  constructor(private readonly jwtService: JwtService) {}
👍

2023-02-21 16:50 UTC, ndaemy commented on src/api/managements/managements.service.ts
> +    const managerExist = await this.managerRepository.findOne({
이럴 때는 managerExist 라는 변수의 역할이 exist 체크에만 사용되는 것이 아니기 때문에 포괄적으로 manager 라고 명명하는게 어떨까 합니다!

2023-02-21 16:50 UTC, ndaemy commented on src/api/managements/entities/user.entity.ts
> +  password: string;
password 는 클라이언트에게 응답될 일이 없는 필드이므로 아래처럼 만들어보면 어떨까 해요 select 를 false 를 주면 기본 응답에서는 빠지는 필드가 됩니다 [참고우](https://typeorm.io/entities#column-options)

```suggestion
  @Column({ select: false })
  password: string;
```

2023-02-21 16:50 UTC, ndaemy commented on src/api/auth/auth.service.ts
> +      accessToken: this.jwtService.sign(payload, {
이러면 payload 를 별도의 변수로 뺀 의미가 없어보여요! 그냥 아래처럼 해도 괜찮을 것 같습니다

```suggestion
    return {
      accessToken: this.jwtService.sign(user, {
```

2023-02-21 16:50 UTC, ndaemy commented on src/api/managements/dto/pw-registration.dto.ts
> +  verifyToken: string;
멤버 변수 사이에는 빈 줄을 띄워주세요!
특히 NestJS에서는 데코레이터가 많다 보니 빈 줄이 없으면 멤버 변수를 구분하기 힘듭니다 😥

2023-02-21 16:50 UTC, ndaemy commented on src/api/managements/dto/pw-registration.dto.ts
> +export class PwRegistrationDto extends PartialType(SendEmailDto) {
PwRegistrationDto 가 SendEmailDto 의 PartialType 이 맞나요? name 필드는 필요없지 않나 싶어서요!

2023-02-21 16:50 UTC, ndaemy commented on src/api/managements/dto/manager-login.dto.ts
> +export class ManagerLoginDto extends PartialType(PwRegistrationDto) {}
1. ManagerLoginDto 가 PwRegistrationDto 의 PartialType 이 맞나요? verifyToken 필드는 필요없지 않나 싶어서요!
2. @nestjs/mapped-types 에는 PickType 같은 다른 형태들도 있습니다! 찾아서 필요에 맞게 사용해보시면 좋을 것 같아요 👍

2023-02-21 16:50 UTC, ndaemy commented on src/api/managements/managements.service.ts
> +    });
생성자랑 메서드 사이에도 빈 줄 하나정도는 넣어주시면 좋을듯합니다!

2023-02-21 16:50 UTC, ndaemy commented on src/api/managements/managements.service.ts
> +@Injectable()
import 문과 class 사이에도 빈 줄 들어가면 좋을 것 같아요!

2023-02-23 10:54 UTC, k0136000 commented on src/api/managements/dto/pw-registration.dto.ts
> +export class PwRegistrationDto extends PartialType(SendEmailDto) {
이메일 부분이 교집합이라 저렇게 연결해 두었는데,
그냥 PartialType지우고 Email을 새로 추가하는게 좋으려나요...??

2023-02-23 10:55 UTC, k0136000 commented on src/api/managements/dto/manager-login.dto.ts
> +export class ManagerLoginDto extends PartialType(PwRegistrationDto) {}
아 선택하는 방법도 있군요!! 
바로 적용하겠습니다!!

2023-02-23 14:35 UTC, k0136000 commented on src/api/auth/auth.service.ts
> +      accessToken: this.jwtService.sign(payload, {
이친구를 저 위에 과정을 거치지 않고 바로 user에 넣어버리면 
Error: Expected "payload" to be a plain object.
에러가 뜨더라구요..
일단은 payload로 넣겠습니다!

2023-02-23 14:54 UTC, k0136000 commented on src/api/auth/auth.module.ts
> +      signOptions: { expiresIn: process.env.JWT_EXPIRES_IN },
이 코드가 없어도 되네요..??
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-02-23 14:54 UTC, k0136000 commented on src/api/auth/auth.module.ts
> +      signOptions: { expiresIn: process.env.JWT_EXPIRES_IN },
passport 헷갈리는군요..

2023-02-27 14:44 UTC, ndaemy approved these changes
드디어 고고 가보자고

2023-02-27 14:44 UTC, ndaemy commented on src/api/auth/auth.module.ts
> +      useFactory: async (config: ConfigType<typeof authConfig>) => ({
👍

2023-02-27 14:44 UTC, ndaemy commented on src/api/auth/auth.service.ts
> +      accessToken: this.jwtService.sign(payload, {
...?! 그건 뭐지 🤔 일단 고고하고 나중에 함 같이 보시졍

2023-02-27 17:28 UTC, merged