assets api 기본 세팅, 데이터 형식
mju-likelion/ballantines pull request #3
Opened 2023-02-09 04:46 UTC by ChoiWonYu

2023-02-09 05:48 UTC, harksu reviewed
현실적으로 아마 이제 제가 서버단에 커멘트를 다는일이 많지는 않을 것 같아요! 
최대한 시간을 내서, 부족하지만 작은 저의 의견을 내러 오도록 하겠습니다.
화이팅! 💯

2023-02-09 05:48 UTC, harksu commented on src/api/assets/assets.service.ts
> +    return part;
참 nest 철학이라고는 하지만, 단순히 매개변수로 넘겨서 그 매개변수를 다시 반환해서 받는 형식은 봐도봐도 적응이 안되네요ㅋㅋㅋㅋ...

Part에서 유효성 검사 먼저 이루고 서비스단에서 반환하는 로직 좋은 것 같습니다 👍

2023-02-09 05:48 UTC, harksu commented on src/api/assets/assets.service.ts
> +  async getAgreement() {
이것도 getAgreement라는 이름은 동의를 얻는가? 라는 의미인 것 같은데, 반환값이 string인건 노리신걸까요~? boolean이 더 적합해보입니다만 🤔

2023-02-09 05:48 UTC, harksu commented on src/api/assets/data.ts
> +        '왜 프론트엔드 파트를 선택하게 되었고 본인이 생각하는 프로젝트 내에서 프론트엔드 파트의 역할을 말씀해주세요.',
여기서 말씀해주세요~ 작성해주세요~ 서술해주세요~ 는 추후에 다시 정리해서 통일하여 드리겠습니다! 번거롭더라도 나중에 수정 부탁드려요 👍

2023-02-09 06:10 UTC, ChoiWonYu commented on src/api/assets/assets.service.ts
> +  async getAgreement() {
getAgreement는 개인 정보 처리 방침 동의서를 내려주는 메서드입니당

2023-02-09 17:05 UTC, ndaemy requested changes

2023-02-09 17:33 UTC, ChoiWonYu commented on src/api/assets/entity/agreement.entity.ts
> +  updatedAt: string;
아하 따로 있었군요!

2023-02-10 13:22 UTC, ndaemy requested changes
아직 전부 리뷰드린게 아니라서, 수정 이후에 멘션 한 번만 주세요!

2023-02-10 13:22 UTC, ndaemy commented on src/api/assets/assets.controller.ts
> +  }
RESTful api 명명법 상, 리소스 생성은 POST method + plural form (복수형) 입니다.
따라서, `POST /api/assets/question` 가 아니라 `POST /api/assets/questions` 가 되어야 맞습니다.

2023-02-10 13:22 UTC, ndaemy commented on src/api/assets/assets.service.ts
> +    }
요걸 pipe 를 사용하든가 해서 더 이쁜 코드로 만들 수는 있을 것 같은데, 일단 급하면 넘어가시져!
저도 찾아봤는데 빠르게 답을 찾진 못했어서요.. 😢

2023-02-10 13:22 UTC, ndaemy commented on src/api/assets/assets.service.ts
> +    const resultQuestions = commonQuestions.concat(questionArray);
요건 concat 보다는 아래처럼 더 많이 씁니다!

```suggestion
    const resultQuestions = { ...commonQuestions, ... questionArray };
```

2023-02-10 13:22 UTC, ndaemy commented on src/api/assets/assets.service.ts
> +    });
위의 변수명이 commonQuestions 였다면, 이것도 비슷하게 partQuestions 가 되는게 더 통일성 있지 않을까 싶어요!

2023-02-10 13:22 UTC, ndaemy commented on src/api/assets/entity/agreement.entity.ts
> +  createAt: Date;
DateColumn 들은 type을 별도로 지정해주지 않으면 datetime 로 들어가는데, timestamp로 별도로 지정한 이유가 있나요?

2023-02-10 13:22 UTC, ndaemy commented on src/api/assets/entity/question.entity.ts
> +}
여기에 order 같은 필드가 있어야 할 것 같아요! 없다면, 순서가 뒤죽박죽으로 반환될 가능성이 있으니까요!

2023-02-11 02:57 UTC, ChoiWonYu commented on src/api/assets/assets.service.ts
> +    }
저도 pipe로 시도하다가 바꿨습니다..ㅠㅠ

2023-02-11 03:00 UTC, ChoiWonYu commented
@ndaemy 2차 수정 확인부탁드립니다...!

2023-02-12 05:24 UTC, k0136000 commented on src/api/assets/assets.service.ts
> +    }
아 pipe를 써도 되네요

2023-02-12 05:26 UTC, k0136000 approved these changes
확인 완료 했습니다!
고생하셨습니다!!

2023-02-12 05:42 UTC, harksu approved these changes
👍  통일만 해주시면 좋을 것 같습니다 :) 아무래도 실제로 통신하면서 버그 잡는게 더 수월할 것 같아요

2023-02-12 05:42 UTC, harksu commented on src/api/assets/data.ts
> +        '왜 프론트엔드 파트를 선택하게 되었고 본인이 생각하는 프로젝트 내에서 프론트엔드 파트의 역할을 말씀해주세요.',
이거 작성해주세요로 통일해주세요 :)

2023-02-12 05:42 UTC, harksu commented on src/api/assets/data.ts
> +    ① 이 개인정보처리방침은 2022년 3월 1일 부터 적용됩니다.`,
이것도 2023년이 맞을 것 같네요!

2023-02-12 15:21 UTC, ndaemy commented on src/api/assets/assets.service.ts
> +  async getAgreement() {
naming 관련해서 짚을까 하다가 그냥 패스했는데 이미 리뷰가 달렸으니 저도 의견 내볼게여 ✋ 
nest g resource 를 이용해서 기본 생성 리소스를 만들어보면 create, findAll, findOne, update, remove 이렇게 만들어져요 그래서 저도 applications 컨트롤러를 만들 때 이 네이밍을 이용했는데, get 이나 set 은 OOP의 getter, setter method 이름하고 겹치는 부분이 있다보니 이렇게 인지의 혼동이 올 수 있을 것 같아서, 컨트롤러하고 서비스 이름을 아래처럼 바꿔보면 어떨까 제안해봅니다

```plain
findQuestions // 혹은 findAllQuestions
createQuestion
findAgreement
createAgreement
```

2023-02-12 15:21 UTC, ndaemy commented on src/api/assets/assets.service.ts
> +      Questions[part]?.map(async (question, idx) => {
이거 다른 곳에서도 리뷰 달았었는데, 최근에는 idx보다는 i나 index 로 쓰는걸 더 많이 보게 되는 것 같아요! 단순 참고용 정도의 의견입니다

2023-02-12 15:21 UTC, ndaemy commented on src/api/assets/assets.service.ts
> +    const keys = Questions && Object.keys(Questions || {});
이 코드의 의도가.. 뭔가요..?

2023-02-12 15:21 UTC, ndaemy commented on src/api/assets/entity/agreement.entity.ts
> +  createAt: Date;
1. 이 두 녀석은 보통 createdAt, updatedAt 이라고 이름 붙이는게 더 흔해요! 하나는 수동태고 하나는 자동사네요 ㅋㅋㅋㅋ
2. 이렇게 두 개를 쓰는 경우 보통은 createdAt 이 먼저 나오고, 이 두 녀석이 가장 마지막 필드로 만들어주는 경우가 흔합니다. 이건 뭐.. 팀별 컨벤션일 것 같은데, 우리는 이 녀석들 맨 뒤로 넣어보는거 어떠세요??

2023-02-12 15:21 UTC, ndaemy commented on src/api/assets/entity/question.entity.ts
> +  part: string;
👍

2023-02-12 15:30 UTC, ChoiWonYu commented on src/api/assets/assets.service.ts
> +    const keys = Questions && Object.keys(Questions || {});
이 메서드는 단순히 파트별 질문을 DB에 넣기 위한 메서드라서
질문이 바뀌는 것이 아니면 쓸 일이 없는 메서드입니다
보통 단순 데이터를 DB에 넣는 작업을 하는 메서드는 유지를 하나요? 아니면 배포 전에 삭제하나요??

2023-02-13 14:47 UTC, ndaemy commented on src/api/assets/assets.service.ts
> +    const keys = Questions && Object.keys(Questions || {});
그냥 안만들죠 DB에 다이렉트로 때려박고 말지 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-02-13 14:47 UTC, ndaemy approved these changes

2023-02-13 15:58 UTC, merged